= About Assert That Event Processor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and later
:keywords: mule, esb, tests, qa, quality assurance, verify, functional testing, unit testing, stress testing

The Assert That Event Processor allows you to run assertions in order to validate the state of a Mule Event's content. +
This Event Processor can be used to validate the Mule Event after the production code runs.

For example, to assert that a payload is equal to a certain value, you can configure the Assert-That processor using the equalTo() matcher.

[source,xml,linenums]
----
<munit-tools:assert-that
  expression="#[payload]"
  is="#[MunitTools::equalTo('example')]"
  message="The payload should be ‘example’"/>
----

Or you can also check if the payload is null using the nullValue() matcher.


[source,xml,linenums]
----
<munit-tools:assert-that
  expression="#[payload]"
  is="#[MunitTools::nullValue()]"
  message="The payload is null"/>
----

If this assertion fails, the processor throws a `java.lang.AssertionError`.

== See Also

* xref:munit-matchers.adoc[About MUnit Matchers]
* xref:fail-event-processor.adoc[About Fail Event Processor]
* xref:set-event-processor.adoc[About Set Event Processor]
* xref:mock-message-processor.adoc[About Mock When Event Processor]
* xref:verify-message-processor.adoc[About Verify Event Processor]