= About Coverage in Maven
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Since MUnit 2.x, the coverage report goal is properly integrated with the maven reporting section. Coverage Reports are
generated during Maven's site lifecycle, during the "coverage-report" goal.

.MUnit Coverage - Sample Maven configuration
[source,xml,linenums]
----
<plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <version>${munit.version}</version>

    <executions>
        <execution>
            <id>test</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
                <goal>coverage-report</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <coverage>
            <runCoverage>true</runCoverage>
            <failBuild>false</failBuild>

            <requiredApplicationCoverage>75</requiredApplicationCoverage>
            <requiredResourceCoverage>50</requiredResourceCoverage>
            <requiredFlowCoverage>50</requiredFlowCoverage>

            <formats>
                <format>console</format>
                <format>html</format>
            </formats>
        </coverage>
    </configuration>
</plugin>
----

== Coverage report types

When enabling MUnit Coverage, you only see a summary report in the console. By default, no other action is taken, so it
is merely informative.

This is how a summary report looks like:

[source,console]
----
===============================================================================
MUnit Coverage Summary
===============================================================================
 * Resources: 2 - Flows: 3 - Processors: 4
 * Application Coverage: 75.00%
====================================================================================
----

But a console report is not your only option. MUnit Coverage offers three types of reports:

* The *Console* report, as shown above, is printed to the console. It works with the summary report and shows an
  overview of the MUnit run, with a count of all resources, flows, and processors, as well as the overall application
  coverage level, and any warnings and errors there may be.
* The *HTML* report shows the same information, which you can view in any web browser. To access the report, browse your
  application folder structure to the path `${application.path}/target/site/munit/coverage/`. Locate the file
  `summary.html`, which is the starting point of the report and lets you navigate through all the data.
* The *JSON* report shows the same information as the _HTML_ report, in a JSON format. To access the JSON report, locate
  the file `${application.path}/target/site/munit/coverage/munit-coverage.json` inside your application folder
  structure.

To enable the report generation, add the following configuration:

.MUnit Coverage - Report Configuration
[source,xml,linenums]
----
<coverage>
    <runCoverage>true</runCoverage>

    <formats>
        <format>console</format> <1>
        <format>html</format>    <2>
        <format>json</format>    <3>
    </formats>
</coverage>
----
<1> Console report
<2> HTML report
<3> JSON report

[TIP]
--
You can have none, one, or all the report types added to your configuration.
--

To configure, for example, the JSON report generation, you need to add the following configuration in your `pom.xml`
file:

[source,xml,linenums]
----
<coverage>
    <runCoverage>true</runCoverage>

    <formats>
        <format>json</format>
    </formats>
</coverage>
----

== Configuring coverage requirements

One of the features of MUnit Coverage is to fail the build if a certain coverage level is not reached.

MUnit Coverage handles three different levels:

* *Application*: The overall coverage of all your application.
* *Resource*: The coverage level of each individual Mule configuration file.
* *Flow*: The coverage of event processors in each flow.

Here is how to define the required coverage levels:

.MUnit Coverage - Require Coverage
[source,xml,linenums]
----
<coverage>
    <runCoverage>true</runCoverage>
    <failBuild>true</failBuild>

    <requiredApplicationCoverage>75</requiredApplicationCoverage>
    <requiredResourceCoverage>50</requiredResourceCoverage>
    <requiredFlowCoverage>50</requiredFlowCoverage>
</coverage>
----

[NOTE]
--
Each value represents a percentage.
--
[NOTE]
--
If a percentage is not defined, it defaults to -1, which indicates that no requirements are defined for said level, and
therefore the build will not fail due to low coverage.
--

If you define coverage levels but set the property `failBuild` to *false*, and then the levels are not reached, a
warning shows up in the MUnit Coverage summary, like in the following example:

[source,console]
----
===============================================================================
MUnit Coverage Summary
===============================================================================
 * Resources: 2 - Flows: 3 - Processors: 4
 * Application Coverage: 75.00%

----------------------------- WARNING --------------------------------------
 * Flow: file2.xml -> file2Flow1 coverage is below defined limit. Required: 50.0% - Current: 00.00% <1>
====================================================================================
----
<1> Warning detailing which coverage level was not met, and where it happened.

== Ignoring a flow or a file

Another feature is the ability to ignore either a flow or a file. This way, the ignored resource:

* Does not count as coverage data.
* Does not affect the overall number of message processors.
* Does not cause a build to fail if the flow is not tested or if the flow does not reach coverage metrics.

Here is how you define flows and files to be ignored:

.MUnit Coverage - Ignore both flows and files
[source,xml,linenums]
----
<coverage>
    <runCoverage>true</runCoverage>
    <failBuild>true</failBuild>

    <requiredApplicationCoverage>100</requiredApplicationCoverage>
    <requiredResourceCoverage>100</requiredResourceCoverage>
    <requiredFlowCoverage>100</requiredFlowCoverage>

    <ignoreFlows>
        <ignoreFlow>flow-1</ignoreFlow>
        <ignoreFlow>flow-2</ignoreFlow>
        ...
        <ignoreFlow>flow-n</ignoreFlow>
    </ignoreFlows>

    <ignoreFiles>
        <ignoreFile>mule-config-1.xml</ignoreFile>
        <ignoreFile>mule-config-2.xml</ignoreFile>
        ...
        <ignoreFile>mule-config-n.xml</ignoreFile>
    </ignoreFiles>
</coverage>
----

== See Also

* xref:munit-coverage-report.adoc[About Coverage Report]