= Enable Flow Sources
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-deployment-options: acb-ide, studio-ide
:keywords: munit, test, flow sources
:flow_name: http-example-flow
:port: 1234
:payload: 'Hello World!'

The `Enable Flow Sources` element within the MUnit test tells MUnit which flow sources to load and execute for the test.

By default, MUnit doesn't start any of the event sources (flow sources such as triggers and listeners). You must configure which flow sources must start for your tests.

Assume that your application has a flow with an HTTP listener that returns a specific payload:

[source,xml,linenums,subs="verbatim,attributes"]
----
<http:listener-config name="HTTP_Listener_config">
    <http:listener-connection host="localhost" port="{port}"/>
</http:listener-config>

<flow name="{flow_name}">
    <http:listener path="/" config-ref="HTTP_Listener_config"/>
    <set-payload value="#[{payload}]" mimeType="text/plain"/>
</flow>
----

For MUnit to be able to invoke that listener, you must enable the `http-example-flow` in your `enable-flow-source` property within your MUnit test:

[source,xml,linenums,subs="verbatim,attributes"]
----
<http:request-config name="HTTP_Request_config">
    <http:request-connection host="localhost" port="{port}"/>
</http:request-config>

<munit:test name="http-example-test">
    <munit:enable-flow-sources>
        <munit:enable-flow-source value="{flow_name}"/>
    </munit:enable-flow-sources>

    <munit:execution>
        <http:request method="GET" path="/" config-ref="HTTP_Request_config"/>
    </munit:execution>

    <munit:validation>
        <munit-tools:assert-that expression="#[payload]"
                                 is="#[MunitTools::equalTo({payload})]"/>
    </munit:validation>
</munit:test>
----

If the `{flow_name}` value isn't listed as an enabled flow source, your MUnit test fails because it can't initialize the HTTP listener configuration.

MUnit starts flow sources at the beginning of the test and stops them at the end of the test. Flow sources aren't executed during the before-suite/before-test, nor during the after-test/after-suite. +
See xref:before-after-scopes-reference.adoc[Before/After scopes] for more information.
