= Configuring FTP Server Utility in an MUnit Test
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-deployment-options: acb-ide, studio-ide

If you want to test the following Mule application:

[source,xml,linenums]
----
<sftp:config name="SFTP_Config">
    <sftp:connection host="${ftp.host}" port="${ftp.port}" username="${ftp.user}" password="${ftp.password}"/>
</sftp:config>

<configuration-properties file="ftp.properties" />

<flow name="listFlow">
    <sftp:list config-ref="SFTP_Config" directoryPath="."/>
    <foreach>
        <logger level="INFO" message="#[attributes.fileName]"/>
    </foreach>
</flow>
----

The `ftp.properties` in `src/main/resources` has the following content:

[source]
----
ftp.host=localhost
ftp.port=22
ftp.user=max
ftp.password=munittest
----

The username field can't be empty. If you don't have a username-password pair, set the username to `anonymous` and don't set any password. By default, the `anonymous` attribute sets to `true`.

== Install the FTP Server

Depending on the IDE you use, to install the FTP server you must:

. Look for the *MUnit Utils FTP Server* asset:
.. In Anypoint Code Builder, open the Command Palette, look for *MuleSoft: Search in Exchange*, and type *MUnit Utils FTP Server* asset.
.. In Anypoint Studio, go to the *Mule Palette*, click *Search in Exchange*, and look for *MUnit Utils FTP Server*.
. Add the module to your project:
+
[source,xml,linenums]
----
<!-- Ftp Server Dependency -->
<dependency>
    <groupId>com.mulesoft.munit.utils</groupId>
    <artifactId>munit-ftpserver-module</artifactId>
    <version>2.0.1</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
</dependency>
----
+
The MUnit FTP server artifact in your POM file must have the `test` scope.

== Define the FTP Server

Depending on the IDE you use, to define the FTP server you must:

. Change the FTP server attributes according to the following values:     
+
[%header%autowidth.spread,cols="a,a"]
|===
| Attribute | Value
| Name | `MUnit_FTP_Server_Config`
| Port | `${ftp.port}`
| Username | `${ftp.user}`
| Password | `${ftp.password}`
| Secure | `true`
| homeDir | `${app.home}`
|===
+
[source,xml,linenums]
----
<ftpserver:config name="MUnit_FTP_Server_Config">
    <ftpserver:connection port="${ftp.port}" username="${ftp.user}" password="${ftp.password}" secure="true" homeDir="${app.home}"/>
</ftpserver:config>
----
+
.. In Anypoint Code Builer, go to the *global-configs.xml* file and add the FTP server code. 
.. In Anypoint Studio canvas, go to the *Global Elements* tab, select your *MUnit FTP Server Config* element, click *Edit*, and complete the fields.

== Run the Test

After configuring the FTP server you can run the test:

[source,xml,linenums]
----
<munit:test name="listFlowTest" description="Test listFlow" >
    <munit:execution>
        <flow-ref name="listFlow"/>
    </munit:execution>
    <munit:validation>
        <munit-tools:assert-that expression="#[sizeOf(payload)]" is="#[MunitTools::greaterThan(0)]"/>
    </munit:validation>
</munit:test>
----

This FTP accepts any user, so you must not set up a user database or list.

== See Also

* xref:ftp-util.adoc[FTP Util]
