= Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:keywords: munit, testing, unit testing

MUnit is a Mule application testing framework that allows you to easily build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

MUnit is fully integrated with Anypoint Studio, allowing you to create, design and run MUnit tests just like you would Mule applications.

With MUnit you can:

* Create your test by writing Mule code
* Mock processors
* Spy any processor
* Verify processor calls
// COMBAK: This will be enable for RC
// * Create not only unit tests but also integration tests in a local environment -- MUnit allows you to start a local FTP/SFTP or DB server
* Enable or ignore particular tests
* Tag tests
// COMBAK: This will be available for RC
* Check visual coverage in Studio
* Generate coverage reports
// * Debug your tests with Studio

MUnit version 2.2, works with all Mule versions since 4.1.4.



== See Also

* xref:message-processors.adoc[About MUnit Event Processors]