= Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:page-aliases: 4.2@mule-runtime::migration-munit-assert-processor-changes.adoc, 4.2@mule-runtime::migration-munit-mock-processor-changes.adoc, 4.2@mule-runtime::migration-munit.adoc, 4.1@mule-runtime::migration-munit-assert-processor-changes.adoc, 4.1@mule-runtime::migration-munit-mock-processor-changes.adoc, 4.1@mule-runtime::migration-munit.adoc

MUnit is a Mule application testing framework that allows you to easily build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

MUnit version 2.3, works with all Mule versions since 4.0

With MUnit you can:

* Create your test by writing Mule code
* Mock processors
* Spy any processor
* Verify processor calls
* Enable or ignore particular tests
* Tag tests
* Check visual coverage in Studio
* Generate coverage reports

MUnit is fully integrated with Anypoint Studio, allowing you to create, design and run MUnit tests just like you would Mule applications.

MUnit is divided in two main sub modules:

* MUnit
* MUnit Tools

Each module has its own dependency:

.MUnit Dependencies
[source,xml,linenums]
----
<dependency>
	<groupId>com.mulesoft.munit</groupId>
	<artifactId>munit-runner</artifactId>
	<version>2.3.0</version>
	<classifier>mule-plugin</classifier>
	<scope>test</scope>
</dependency>
----


.MUnit Tools dependencies
[source,xml,linenums]
----
<dependency>
	<groupId>com.mulesoft.munit</groupId>
	<artifactId>munit-tools</artifactId>
	<version>2.3.0</version>
	<classifier>mule-plugin</classifier>
	<scope>test</scope>
</dependency>
----

== See Also

* xref:event-processors.adoc[MUnit Event Processors]
