= Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:page-aliases: 4.2@mule-runtime::migration-munit-assert-processor-changes.adoc, 4.2@mule-runtime::migration-munit-mock-processor-changes.adoc, 4.2@mule-runtime::migration-munit.adoc, 4.1@mule-runtime::migration-munit-assert-processor-changes.adoc, 4.1@mule-runtime::migration-munit-mock-processor-changes.adoc, 4.1@mule-runtime::migration-munit.adoc
:page-deployment-options: acb-ide, studio-ide

MUnit is a Mule application testing framework that allows you to build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

MUnit version 3.0 works with all Mule versions since 4.3.

With MUnit you can:

* Create your test by writing Mule code
* Mock processors
* Spy any processor
* Verify processor calls
* Enable or ignore particular tests
* Tag tests
* Check visual coverage in Studio
* Generate coverage reports

You can create, design, and run MUnit tests with the integration MUnit has in Anypoint Studio and Anypoint Code Builder.

MUnit has two main sub modules:

* MUnit
* MUnit Tools

Each module has its dependency:

== MUnit Dependencies
[source,xml,linenums]
----
<dependency>
	<groupId>com.mulesoft.munit</groupId>
	<artifactId>munit-runner</artifactId>
	<version>2.3.0</version>
	<classifier>mule-plugin</classifier>
	<scope>test</scope>
</dependency>
----

== MUnit Tools Dependencies
[source,xml,linenums]
----
<dependency>
	<groupId>com.mulesoft.munit</groupId>
	<artifactId>munit-tools</artifactId>
	<version>2.3.0</version>
	<classifier>mule-plugin</classifier>
	<scope>test</scope>
</dependency>
----

== See Also

* xref:event-processors.adoc[MUnit Event Processors]
* xref:munit-in-studio.adoc[]
* xref:munit-in-acb.adoc[]
