= MUnit Maven Plugin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:keywords: munit, testing, unit testing

MUnit is a composition of several modules, all of which are necessary to run your MUnit test.

MUnit provides a Maven plugin that allows you to run your MUnit tests as part of your continuous integration environment. +
The MUnit Maven Plugin allows you to run MUnit tests from Maven.

== To Set Up MUnit Maven Plugin (Maven)

For MUnit to run properly with Maven, you need to add a few sections to your pom.xml file.

This documentation assumes you have the <munit.version> property in your pom.xml.

* Enable the MUnit Maven plugin, by adding the following section to your pom.xml.
+
.MUnit Maven Plugin
[source,xml,linenums]
----
<build>
  <plugins>
  ...

    <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <version>${munit.version}</version>
      <executions>
        <execution>
          <id>test</id>
          <phase>test</phase>
          <goals>
            <goal>test</goal>
          </goals>
        </execution>
      </executions>
    </plugin>

  ...
  </plugins>
</build>
----
* Add MUnit dependencies to your pom.xml.
+
.Dependencies
[source,xml,linenums]
----
<dependencies>
  ...
  <dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>munit-runner</artifactId>
    <version>${munit.version}</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>munit-tools</artifactId>
    <version>${munit.version}</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
  </dependency>
  ...
</dependencies>
----

* Finally, you need to setup the repositories where Maven will download the MUnit dependencies and Plugin.
+
.Repositories
[source,xml,linenums]
----
<repositories>
  <repository>
    <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>http://repository.mulesoft.org/releases/</url>
      <layout>default</layout>
    </repository>
</repositories>
----
+
.Plugin Repositories
[source,xml,linenums]
----
<pluginRepositories>
  <pluginRepository>
    <id>mulesoft-release</id>
    <name>mulesoft release repository</name>
    <layout>default</layout>
    <url>http://repository.mulesoft.org/releases/</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </pluginRepository>
</pluginRepositories>
----


MUnit has Surefire support built in. No additional configuration is needed. +
The reports can be found under target/surefire-reports.

== How To Handle Parent POM Files

You can declare the MUnit plugin in a parent POM file and every child project under this file can choose to reference this definition.

In order to make a proper use of the MUnit plugin in a parent-child POM relationship, you need to include the MUnit plugin declaration in the `<pluginManagement>` section of your parent `pom.xml` file:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <groupId>org.pirate</groupId>
    <artifactId>pirate-pom</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <munit.version>2.2.0</munit.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.mulesoft.munit.tools</groupId>
                    <artifactId>munit-maven-plugin</artifactId>
                    <version>${munit.version}</version>
                    <executions>
                        <execution>
                            <id>test</id>
                            <phase>test</phase>
                            <goals>
                                <goal>test</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                      <coverage>
                          <runCoverage>true</runCoverage>
                          <failBuild>false</failBuild>
                          <requiredApplicationCoverage>0</requiredApplicationCoverage>
                          <requiredResourceCoverage>0</requiredResourceCoverage>
                          <requiredFlowCoverage>0</requiredFlowCoverage>
                          <formats>
                              <format>console</format>
                              <format>html</format>
                          </formats>
                      </coverage>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
----

This pirate-pom project declares the MUnit Maven plugin in its plugin management section, which defines a global configuration that each child under this parent can choose to reference, override or even ignore.

== To Inherit Parent's Plugin

To inherit the MUnit plugin in your child POM files, you need to reference it in a _<plugin>_ section of each child _POM_ file individually:

.POM child file sample
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.pirate</groupId>
        <artifactId>pirate-pom</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>ninja</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule</packaging>
    <name>Mule ninja Application</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <app.runtime>4.1.1</app.runtime>
        <munit.version>2.2.0</munit.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.mulesoft.munit.tools</groupId>
                <artifactId>munit-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    </project>
----

This quick sample references _pirate-pom_ file as its parent and then declares the MUnit plugin in a `<plugin>` section without specifying its `<version>` because MUnit plugin configuration is being inherited from the `<pluginManagement>` section in the parent.


//_THIS
== To Ignore a Parent's Plugin

Each child project under a parent `pom` file can choose to ignore the plugin referenced in the  parent's plugin management section and not implement the plugin declared there.

By not declaring the Munit Plugin in your `<plugin>` section, you avoid inheriting the plugin declared in *pirate-pom*:

.Child POM file not inheriting the MUnit Maven Plugin
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.pirate</groupId>
        <artifactId>pirate-pom</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>ninja</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule</packaging>
    <name>Mule ninja Application</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <mule.version>4.1.0</mule.version>
        <munit.version>2.2.0</munit.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mule.tools.maven</groupId>
                <artifactId>mule-app-maven-plugin</artifactId>
                <version>${mule.tools.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <copyToAppsDirectory>true</copyToAppsDirectory>
                </configuration>
            </plugin>

        </plugins>
    </build>
    </project>
----

//_to-verride-parent-plugin.adoc

== To Override a Parent's Plugin

When inheriting the plugin from a parent POM file, you can also choose to override the parent's configuration, but keep in mind that overriding completely suppresses the original configuration, requiring you to declare all necessary configurations again:

.Coverage configuration in parent POM file
[source,xml,linenums]
----
<coverage>
	<runCoverage>true</runCoverage>
	<failBuild>false</failBuild>
	<requiredApplicationCoverage>0</requiredApplicationCoverage>
	<requiredResourceCoverage>0</requiredResourceCoverage>
	<requiredFlowCoverage>0</requiredFlowCoverage>
	<formats>
		<format>console</format>
		<format>html</format>
	</formats>
</coverage>
----


.POM child file overriding coverage report's format
[source,xml,linenums]
----
<plugin>
	<groupId>com.mulesoft.munit.tools</groupId>
	<artifactId>munit-maven-plugin</artifactId>
	<configuration>
		<coverage>
			<runCoverage>true</runCoverage>
			<formats>
				<format>html</format>
			</formats>
		</coverage>
	</configuration>
</plugin>
----

In this example, this child project is overriding the console coverage report, replacing it only by the HTML one, but since the values from the other elements in the parent (`<failBuild>`, `<requiredApplicationCoverage>`, `<requiredResourceCoverage>`, `<requiredFlowCoverage>`) are not being referenced, this child file won't inherit them and the default values will apply.

//to-configure-munit-mavne-plugin
== To Configure MUnit Maven Plugin From the POM File
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Additional argument lines

Since the tests are being run in a new JVM, additional argument lines can be specified
to the JVM. Each argument should be specified in separate `argLine`.

.Argument lines
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <argLines>
          <argLine>-XX:MaxPermSize=512m</argLine>
          <argLine>-Xmx1024m</argLine>
      </argLines>
      ...
    </configuration>
  </plugin>
</plugins>
----

== To Enable Coverage

To enable MUnit Coverage, add the following configuration to the MUnit Plugin:

.MUnit Coverage - Minimal Configuration
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <coverage>
        <runCoverage>true</runCoverage>   //<1>
      </coverage>
      ...
    </configuration>
  </plugin>
</plugins>
----
<1> This enables the coverage feature

== To Set a Minimum Coverage Level

One of the features of MUnit Coverage is to fail the build if a certain coverage level is not reached.

To make the build fail, add the following lines to the configuration:

.MUnit Coverage - Fail Build
[source,xml,linenums]
----
<coverage>
  <runCoverage>true</runCoverage>
  <failBuild>true</failBuild>       //<1>
</coverage>
----
<1> Enable *Fail Build Feature*

The next step is to define the coverage levels.

MUnit Coverage handles three different levels:

* Application
* Resource
* Flow

Here is how to define the required coverage level:

.MUnit Coverage - Require Coverage
[source,xml,linenums]
----
<coverage>
  <runCoverage>true</runCoverage>
  <failBuild>true</failBuild>

  <requiredApplicationCoverage>20</requiredApplicationCoverage>
  <requiredResourceCoverage>10</requiredResourceCoverage>
  <requiredFlowCoverage>5</requiredFlowCoverage>
</coverage>
----

TIP: Each value represents a percentage.

If you define coverage levels but set the property `failBuild` to *false*, if the levels are not reached, a warning shows up in the MUnit Coverage summary.

Something like this:

[source,console,linenums]
----
INFO] [CoverageManager] Printing Coverage Report...
[INFO] ===============================================================================
[INFO] MUnit Coverage Summary
[INFO] ===============================================================================
[INFO]  * Resources: 3 - Flows: 6 - Message Processors: 7
[INFO]  * Application Coverage: 71.43%
[INFO]
[WARNING] ----------------------------- WARNING --------------------------------------
[WARNING]  * Application coverage is below defined limit. Required: 100.0% - Current: 71.43%  //<1>
----
<1> Warning detailing which coverage level wasn't met

TIP: If no level is defined, -1 is assumed, which indicates that the build won't fail due to lack of coverage.

== To Ignore Flows for Coverage Report

.MUnit Coverage - Ignoring Flows
[source,xml,linenums]
----
<coverage>
  <ignoreFlows>
	  <ignoreFlow>the-name-of-your-flow</ignoreFlow>       //<1>
  </ignoreFlows>
</coverage>
----
<1> The name of the flow you want to ignore.

This is a list, so you can ignore as many flows as you need.

== Dynamic Ports

[IMPORTANT]
MUnit 2.2 and later introduce the `dynamic-port` global element, that allows you to define dynamic ports at the MUnit suite level. +
Using this element instead of the plugin configuration described below allows you to set the dynamic port both from Maven and Studio. +
See xref:dynamic-ports.adoc[Dynamic Ports] to learn how to configure this element.


When testing a Mule application in a continuous integration (CI) environment, you might encounter the following scenario:

`Your application tries to open a specific port. The port is already in use. The application fails with a port binding exception.`

The easy solution to this problem is to have your application use a free port.
The MUnit Maven Plugin comes with a built-in feature to do just that.

`MUnit Dynamic Ports` instructs the MUnit Maven Plugin to look for unbound ports and reserve them before running the tests over the Mule application. Each port selected is placed in a system property under the name indicated in the configuration.
The application can acquire the port number through the use of placeholders afterward.

TIP: The Ports to be selected by the plugin are taken from the following range: `[40000,50000)`

[CAUTION]
--
Dynamic Ports feature is only available as part of the MUnit Maven Plugin. +
You can not expect this feature to work when running tests from inside Anypoint Studio.
--

=== Enabling Dynamic Ports

To enable the feature, you need to add the following code to the `configuration` section of the MUnit Maven Plugin:

.Dynamic Ports Configuration
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
    ...
    <dynamicPorts>
      <dynamicPort>a.dynamic.port</dynamicPort>
    </dynamicPorts>
    ...
    </configuration>
  </plugin>
</plugins>
----

If you have the `${http.port}` placeholder in your application, the configuration looks something like:

.Example
[source,xml,linenums]
----
<dynamicPorts>
  <dynamicPort>http.port</dynamicPort>
</dynamicPorts>
----

==== Preparing Your Application

A placeholder must parametrize the part of the application trying to make use of a port. +
For instance, you may want to have your Mule application listening for HTTP traffic. To do that you should provide the following configuration:

.HTTP Simple Application
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config">
  <http:listener-connection host="0.0.0.0" port="8081" />
</http:listener-config>

<flow name="httpFlow">
  <http:listener path="/" config-ref="HTTP_Listener_config"/>
</flow>
----

Now this application always listens in port `8081`. To make it dynamic, change it to:

.HTTP Simple Application with dynamic port
[source,xml,linenums]
----
<http:listener-config name="HTTP_Listener_config">
  <http:listener-connection host="0.0.0.0" port="${http.port}"/> //<1>
</http:listener-config>

<flow name="httpFlow">
  <http:listener path="/" config-ref="HTTP_Listener_config"/>
</flow>
----
<1> Notice the placeholder `${http.port}`.

With the application coded in this way and the configuration of Dynamic Ports in place, your application starts each run listening on a different port.

== Enable surefire reports

MUnit has built-in support for Surefire. No additional configuration is needed for this but it can be disabled if not needed.


//_TODO: Where? Properties? pluginConfig?
.Disabling surefire reports
[source,xml,linenums]
----
<enableSurefireReports>false</enableSurefireReports>
----

The reports can be found under `${project.build.directory}/surefire-reports`.

By default, it is set to `true`.


//_TODO:munit-maven-support.adoc
== To Run MUnit Tests for a Mule Application (MUnit Maven Plugin)

.Running MUnit tests in a Single Resource Mule project.
[source,console]
----
mvn clean test
----

== To Run a Specific MUnit Test Suite (MUnit Maven Plugin)

You can instruct MUnit Maven Plugin to run only tests that belong to a specific test suite.

To do this, we use the property `munit.test`.

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>
----

The property `munit.test` accepts regular expressions. The expression is applied to the name of the MUnit Test Suite file. The regular expression language is the Java implementation. +
This path is relative to src/test/munit.

The following is a valid example:
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*
----

You can leverage this feature by adding naming conventions to your MUnit Test suites.

== To Run Specific MUnit Tests (MUnit Maven Plugin)

In the same way that you instruct MUnit to run one test suite, you can also tell it to run a specific test inside that test suite. To do so, we again make use of the property `munit.test`, with one addition:

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

The addition is the special character `#`. To the right of it, you should type the test name. It also accepts regular expressions. The expression is applied to the attribute `name` of the MUnit Test.

The following is a valid example:
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*#.*test-scenario-1.*
----

[TIP]
--
The tests inside the MUnit Test Suite that don't match the regular expression is flagged as *ignored*.
--

== To Run Tests Using a Specific Tag (MUnit Maven Plugin)

You can choose to run only the tests that you grouped under one specific tag.

[source,console]
----
mvn clean test -Dmunit.tags=<munit-tag>
----

== To Skip All Tests (MUnit Maven Plugin)

When building your application, you may want to prevent a test from running. MUnit leverages the same mechanism as Maven, so if you wish to skip tests, you can make use of the parameter `skipTests`.

.Skipping Tests example
[source,console]
----
mvn clean package -DskipTests
----


== To Run Specific Tests

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <configuration>
      ...
      <munitTest>example-MunitTest-suite.xml</munitTest>
      ...
    </configuration>
  </plugin>
</plugins>
----

== To Run Tests With Specific Tags

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <configuration>
      ...
      <munitTags>exampleMunitTag</munitTags>
      ...
    </configuration>
  </plugin>
</plugins>
----

You can specify more than one tag by separating them using a comma.

== To Skip MUnit Tests

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <configuration>
      ...
      <skipMunitTests>True</skipMunitTests>
      ...
    </configuration>
  </plugin>
</plugins>
----


// CONFIGURATION

== To Skip Tests After One Suite Fails

MUnit allows you to skip the rest of the tests if one test suite fails. +
If not specified, this value is false by default.

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-maven-plugin</artifactId>
      <configuration>
      ...
      <skipAfterFailure>true</skipAfterFailure>
      ...
    </configuration>
  </plugin>
</plugins>
----

== To Specify the Runtime Product

MUnit allows you to specify the runtime version in which your applications being tested will run.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <runtimeVersion>1.2.3</runtimeVersion>
      ...
    </configuration>
  </plugin>
</plugins>
----

== To Specify The Runtime

MUnit allows you to specify the type of runtime in which your applications being tested will run. +
The two possible values are MULE for community edition, and MULE_EE for Enterprise Edition.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <runtimeProduct>MULE</runtimeProduct>
      ...
    </configuration>
  </plugin>
</plugins>
----

== To Specify The JVM

MUnit allows you to specify the jvm (or the java executable) in which your applications being tested will run.
The property should be populated with the path to the executable.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <jvm>/path/to/jdk/bin/java</jvm>
      ...
    </configuration>
  </plugin>
</plugins>
----

From the command line, the property is `-Dmunit.jvm`

== Environment Variables

To set additional environment variables during the test run, you can specify
them with the respective key and value.

.Additional Environment Variables
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <environmentVariables>
        <MY_ENV>exampleValue</MY_ENV>
        <MY_OTHER_ENV>val2</MY_OTHER_ENV>
      </environmentVariables>
      ...
    </configuration>
  </plugin>
</plugins>
----

Environment variables can be used to replace placeholders such as `${MY_ENV}`
(using the example above).

== Redirect Test Output to File

When running several tests, the build output can get very complex to read. You may want
to redirect the output of each Test suite to a file. This way what remains in the build
output will be the test results and to check the standard output of each test suite you can find it
in its respective file.

These files will be located in the `testOutputDirectory` folder following this naming convention:
`munit.${suiteName}-output.txt`, where the `suiteName` represents the name of the XML file relative to the
MUnit test folder.

The test run output that doesn't belong to a particular suite won't be printed to keep the build output clean, but it can be enabled by running maven in _debug_ mode.

.Redirect test output to file
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <redirectTestOutputToFile>true</redirectTestOutputToFile>
      ...
    </configuration>
  </plugin>
</plugins>
----

By default, it is set to `false`

== System Properties Variables

You may wish to define specific system variables needed for your MUnit test to run successfully. The example below shows how you can send them.

.Setting system property variables
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <systemPropertyVariables>
        <my.property.key>my.property.value</my.property.key>
      </systemPropertyVariables>
      ...
    </configuration>
  </plugin>
</plugins>
----

[TIP]
====
Depending on the execution context, the system properties values may vary. When referencing these properties, it is a good practice to override their value to enforce test reproducibility.

You can do so using the ­`-D` argument when running MUnit with Maven. +
Variables passed with the `-D` argument take full priority over any other property.

For example:

`-Dmy.property.key=my.property.another.value`
====

== Test Output Directory

You may want to choose the location where the test output files will be created.
The path specified can be absolute or written as a maven placeholder.

.Test output directory with absolute path
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-maven-plugin</artifactId>
    <configuration>
      ...
      <testOutputDirectory>/my/absolute/path</testOutputDirectory>
      ...
    </configuration>
  </plugin>
</plugins>
----

.Test output directory using maven placeholders
[source,xml,linenums]
----
<testOutputDirectory>${project.build.directory}/my/output/folder</testOutputDirectory>
----

By default, the files will be created in `${project.build.directory}/munit-reports/output/`.

//.munit-maven-plugin-configuration.adoc

== MUnit Maven Plugin Configuration Reference

The MUnit Maven Plugin offers a set of optional parameters that can be configured.

//_NOTE: This params are taken from MUnitMojo.java in munit-runtime code.

.Maven Plugin Parameters
[%header,cols="3,^2,4"]
|===
|Name    |Type | Description

|argLines
|List
|Additional JVM argument lines to set on the test run.

| coverage
| Configuration
| Coverage configuration to be set on the test run.

|dynamicPorts
|List
|Dynamic ports to be set on the test run.

|enableSurefireReports
|boolean
|Set value to `true` to generate MUnit test results in the surefire format. +
*Default value: `true`*

| munitTest
| String
| Name of the MUnit tests to run.

| munitTags
| String
| Name of the MUnit tags. Only tests tagged with these names will run.

| skipMunitTests
| boolean
| Set to `true` when you want to skip all MUnit tests. +
*Default value: `false`*

| skipAfterFailure
| boolean
| Skip all tests if one fails. +
*Default value: `false`*

| munitTestsDirectory
| File
| Directory where the MUnit tests reside. +
*Default value: `${project.build.directory}/test-mule/munit`*


| runtimeVersion
| String
| Version of the Mule runtime in case
By default it runes with the mule-version defined in the pom.xml file of the mule-artifact.json.

| runtimeProduct
| String
| Type of runtime. Expected values are MULE for community edition, and MULE_EE for enterprise edition. +
By default, this value is taken from the requiredProduct parameter in the mule-artifact.json file.

| jvm
| String
| Option to specify the jvm (or path to the java executable) to use.

By default, the JVM will the same VM as the one used to run Maven.

|environmentVariables
|Map
|Additional environment variables to be set on the test run.

|redirectTestOutputToFile
|boolean
|Set value to `true` to redirect the MUnit tests standard output to a file. +
*Default value: `false`*

|systemPropertyVariables
|Map
|System properties to be set on the test run.

|testOutputDirectory
|File
|Directory where the test outputs will be written to. +
*Default value: `${project.build.directory}/munit-reports/output/`*

// THESE PARAMS ARE IN THE CODE, BUT NOT EXPOSED TO THE USER.
// | surefireReportsFolder
// | File
// | Directory where the reports in the surefire format will be written to. +
// *Default value: `${project.build.directory}/surefire-reports/`*

// | pluginVersion
// | String
// | Version of the MUnit Maven Plugin.

// | coverageReportDataFile
// | File
// | Directory where the coverage report data lives. +
// *Default value: `${project.build.directory}/munit-reports/coverage-report.data`*

// | coverageConfigDataFile
// | File
// | Directory where the coverage report configuration file lives. +
// *Default value: ${project.build.directory}/munit-reports/coverage-config.data"*

// |muleWorkingDirectory
// |File
// |Directory to be used as Mule working directory. +
// *Default value: `${project.build.directory}/.mule`*

// | session
// | MavenSession
// |

// |classpathDependencyExcludes
// |List
// |Dependencies to be excluded from the classpath. Must follow the format `groupId:artifactId`.

// | project
// | MavenProject
// | *Required*

// |classpathElements
// |List
// |Additional entries to be appended to the classpath.


|===



== See Also

* xref:to-set-up-munit-maven-plugin.adoc[To Set Up MUnit Maven Plugin]
* xref:munit-maven-plugin.adoc[To Operate the MUnit Maven Plugin]