= MUnit 2.0.0-BETA Changes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: munit, 2.0.0 Beta

We’ve introduced several changes to the MUnit 2.X syntax. Please find below a list of those changes.

== MUnit config

* We removed the attributes mock-connectors and mock-inbounds. They have been replaced with disableFlowSources. +
* We’ve added the exclude-flow-sources

.MUnit config for 1.x
[source,xml,linenums]
----
<munit:config name="munit"
  mock-connectors="false"
  mock-inbounds="false"/>
----

.MUnit config for 2.x
[source,xml,linenums]
----
<munit:config disableFlowSources="true">
  <munit:exclude-flow-sources>
	<munit:flows>
	  <munit:flow value="mockedFlow"/>
      <munit:flow value="mockedFlow2"/>
    </munit:flows>
  </munit:exclude-flow-sources>
</munit:config>
----

== Before/After Flows

This section refers to before-suite, after-suite, before-test, after-test. +
There are no change to the syntax of these scopes, but while in MUnit 1.x we allow as many of any of them as the user wanted in MUnit 2.x we allow only one of each per MUnit Test Suite file.

This restriction will be enforced at deployment and the deploy of the application will fail should any such scope is present more than one time.

== Test Flow


.Test Syntax for MUnit 1.x
[source,xml,linenums]
----
<munit:test name="test-1"
  expectException="java.lang.RuntimeException"
  ignore="false"
  description="Descriptive text"/>
----

.Test Syntax for MUnit 2.x
[source,xml,linenums]
----
<munit:test name="test-1"
  expectedErrorType="type"
  expectedException="java.lang.RuntimeException"
  ignore="false"
  tags="full_regression,smoke"
  description="Descriptive text">

  <munit:behavior>
  </munit:behavior>

  <munit:execution>
	</munit:execution>

  <munit:validation>
	</munit:validation>

</munit:test>
----

== Processors: NameSpace Changes

Processors will change of name space to munit-tools.

== See Also

* xref:mock-processor-changes.adoc[Mock Processor Changes]
* xref:assert-processor-changes.adoc[Assert Processors Changes]
* xref:set-message-processor-changes.adoc[Set Message Processors Changes]