= Run Custom Event Processor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and later
:keywords: mule, esb, tests, qa, quality assurance, verify, functional testing, unit testing, stress testing

The Run Custom event processor allows you to assert the Mule event content against a custom assertion.

Although it's not necessary to add any extra dependencies to your `pom.xml` file, you must your custom assertion class to the `mule-artifact.json` file as an exported resource.

For example, you can define the following assertion in Java:

[source,java,linenums]
----
public class CustomAssertion implements MunitAssertion {

    @Override
    public void execute(TypedValue expression, Object params) throws AssertionError { // <1>
        if (!"Hello World".equals(expression.getValue())) { // <2>
            throw new AssertionError("Error the payload is incorrect");
        }
     }

}
----
<1> Implement the only method in the interface `public void execute(TypedValue expression, Object params) throws AssertionError`
<2> Run your custom logic, which in this case validates that the message's payload is `Hello World`.

And then use the Run Custom Event Processor to run it:

[source,xml,linenums]
----
<munit-tools:run-custom
  assertion="com.example.CustomAssertion" // <1>
  expression="#[payload]"/>
----
<1> The assertion field needs to have the canonical class name of your custom assertion and the class needs to be exported.

To export it when packaging your application, add the `CustomAssertion` to your `mule-artifact.json`

[source,json,linenums]
----
{
    "name": "mule-application",
    "minMuleVersion": "4.2.0",
    "classLoaderModelLoaderDescriptor": {
        "id": "mule",
        "attributes": {
            "exportedResources": [
                "resources/CustomAssertion.java"
            ]
        }
    }
}
----

== See Also

* xref:munit-matchers.adoc[About MUnit Matchers]
* xref:assertion-event-processor.adoc[About Assert That Event Processor]
* xref:set-event-processor.adoc[About Set Event Processor]
* xref:mock-event-processor.adoc[About Mock When Event Processor]
* xref:verify-event-processor.adoc[About Verify Event Processor]
* xref:fail-event-processor.adoc[About Fail Event Processor]