= Set Event Processor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:keywords: munit, testing, unit testing

The Set Event Processor allows you to define a Mule Event. +
This message processor is normally used at the beginning of an MUnit test, to define the first message to send to the flow being tested.

The example below shows how to define a simple payload of a Mule Message:

[source,xml,linenums]
----
<munit:set-event cloneOriginalEvent="false">
  <munit:payload value="#['payload_value']" mediaType="text/plain" encoding="UTF-8"/>
</munit:set-event>
----

The set-event has the cloneOriginalEvent property. If set to true, it clones the event produced by your code. +
By default, the value of this property is false.

The payload element in the Set Event processor has the following attributes:

[%header%autowidth.spread]
|===
|Attribute Name |Description

|`value`
|Defines the value of the payload's message.

|`encoding`
|Defines the encoding of the message. This attribute is optional.

|`mediaType`
|Defines the mime type of the message. This attribute is optional.

|===

You can also use the Set Event processor to define message attributes and event variables:

[source,xml,linenums]
----
<munit:set-event cloneOriginalEvent="false">
  <munit:payload value="#['Example Body']" mediaType="text/plain" encoding="UTF-8"/>

  <munit:attributes value="#[{ method : 'GET', queryParams : { page : '1'}}]" />

  <munit:variables>
    <munit:variable key="variable_key" value="#['example']" mediaType="text/plain" encoding="UTF-8"/>
  </munit:variables>
</munit:set-event>
----

All the properties have the same set of attributes:

[%header%autowidth.spread]
.Property Message Processor's Attributes
|===
|Attribute Name |Description

|`key`
|The key of the property being set.

|`value`
|The content of the property.

|`encoding`
|Defines the encoding of the message. This attribute is optional.

|`mediaType`
|Defines the mime type of the message. This attribute is optional.

|===

You can define as many properties per each scope as you need for your test.

[WARNING]
--
If you define two properties in the same scope with the _same_ key, be aware that one would end up overwriting the other.
--

== See Also

* xref:test-mock-errors-cookbook.adoc[Testing and Mocking Errors]
* xref:fail-event-processor.adoc[Fail Event Processor]
* xref:run-custom-event-processor.adoc[Run Custom Event Processor]