= Using Utility Classes From a Test
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When developing test cases, you might want to use Java classes located in `src/test/java`. You can use Java classes through Java Module or through DataWeave.

For the following example, assume that your class is located in `src/test/java/com/example/MyUtilClass.java`:

.MyUtilClass
[source, java, linenums]
----
package com.example.test;

public class Helper {

  public static long getCurrentMillis() {
    return System.currentTimeMillis();
  }

}
----

[CAUTION]
====
The package of the class needs to be exported in the `mule-artifact.json` file:
[source, json]
----
{
  "minMuleVersion": "4.x.x",
  "classLoaderModelLoaderDescriptor": {
    "id": "mule",
    "attributes": {
      "exportedPackages": [
        "com.example.test"
      ]
    }
  }
}
----
====


== Using DataWeave

To invoke static methods using DataWeave you must add the `java!` prefix to the package name of the class:

.Using a Class in DataWeave
[source, xml, linenums]
----
<munit:test name="usingJavaInDW">
    <munit:behavior>
        <set-variable variableName="number" value="#[java!com::example::test::Helper::currentMillis()]" />
    </munit:behavior>
    <munit:execution>
        <flow-ref name="myFlow"/>
    </munit:execution>
</munit:test>
----

== Using Java Module

. Ensure that the Java module is in your project:
+
.Java Module dependency
[source, xml, linenums]
----
<dependency>
    <groupId>org.mule.module</groupId>
    <artifactId>mule-java-module</artifactId>
    <version>${javaModule.version}</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
</dependency>
----
. Use any of the Java Module's operations. +
In this case, invoke a static method of a class:
+
.Using a class with the Java Module
[source, xml, linenums]
----
<munit:test name="usingJavaInDW">
    <munit:behavior>
        <set-variable variableName="number" value="#[java!com::example::test::Helper::currentMillis()]" />
    </munit:behavior>
    <munit:execution>
        <flow-ref name="myFlow"/>
    </munit:execution>
</munit:test>
----