= MUnit Verify Event Processor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 and newer
:keywords: munit, testing, unit testing
:page-aliases: verify-message-processor.adoc
:page-deployment-options: acb-ide, studio-ide

The MUnit Verify event processor validates that a specified event processor was called a certain number of times during a MUnit test. Use it to confirm that your flow executed the expected processors with the expected attributes, even without creating a mock for them.

[source,xml,linenums]
----
<munit-tools:verify-call processor="http:request" atLeast="1">
   <munit-tools:with-attributes>
       <munit-tools:with-attribute attributeName="method" whereValue="#['GET']" />
   </munit-tools:with-attributes>
</munit-tools:verify-call>
----

[%header%autowidth.spread]
|===
|Attribute Name |Description

|`eventProcessor`
|Describes which event processor you want to mock. The description takes the form `\{name-space}:\{event-processor-name}`. It supports regular expressions.

|`times`
|*(Default = 1.)* Defines the verification as successful if the event processor was called _N_ and only _N_ number of times.

|`atLeast`
|Defines the verification as successful if the event processor was called a minimum of _N_ number of times.

|`atMost`
|Defines the verification as successful if the event processor was called maximum of _N_ number of times.

|===

The attributes `times`, `atLeast`, `atMost`, are mutually exclusive.

The `eventProcessor` attribute accepts regular expressions. For example, you can create the same verification as `.*:request` to verify for an event processor named request, disregarding which namespace the event processor belongs to. The regular expression language is the same as Java.

== See Also

* xref:assertion-event-processor.adoc[Assert That Event Processor]
* xref:fail-event-processor.adoc[Fail Event Processor]
* xref:run-custom-event-processor.adoc[Run Custom Event Processor]
* xref:set-event-processor.adoc[Set Event Processor]
* xref:mock-event-processor.adoc[Mock When Event Processor]